import type { ExamGoal, Subject, Task, StudyDay, GrowthCard, CardDeck, Resource, Question, KnowledgeNode, Note, Annotation, AppSettings } from "./types";

// Static seed data - use FIXED dates to avoid hydration mismatch between server and client
// These are placeholder dates for initial seed data only.
const SEED_DATE_ONLY = "2026-07-30";
const SEED_TODAY = "2026/7/30 22:00:00";

export const seedExam: ExamGoal = {
  examName: "2027 考研初试",
  school: "哈尔滨工业大学重庆研究院",
  major: "828 物理化学",
  examDate: "2026-12-20",
  startDate: SEED_DATE_ONLY,
  examGoalCreatedAt: SEED_DATE_ONLY,
  weeklyDays: "6",
  weekdayHours: "3.5",
  weekendHours: "8",
  baseline: "专业课热力学基础薄弱，数学二第一轮推进中。",
};

export const seedSubjects: Subject[] = [
  {
    id: "s-politics",
    name: "政治",
    type: "公共课",
    maxScore: "100",
    targetScore: "70",
    currentProgress: "马克思主义原理",
    currentMastery: "有些模糊",
    weeklyHours: "6",
    hasPastPapers: true,
    hasSolutions: true,
    hasReferences: true,
    round: "第一轮",
    layer: "Layer 1",
    focus: "马原",
    risk: "正常",
  },
  {
    id: "s-english",
    name: "英语一",
    type: "公共课",
    maxScore: "100",
    targetScore: "70",
    currentProgress: "2010-2025 真题阅读",
    currentMastery: "基本理解",
    weeklyHours: "8",
    hasPastPapers: true,
    hasSolutions: true,
    hasReferences: true,
    round: "第一轮",
    layer: "Layer 1",
    focus: "长难句",
    risk: "正常",
  },
  {
    id: "s-math",
    name: "数学二",
    type: "公共课",
    maxScore: "150",
    targetScore: "120",
    currentProgress: "一元函数积分",
    currentMastery: "有些模糊",
    weeklyHours: "14",
    hasPastPapers: true,
    hasSolutions: false,
    hasReferences: true,
    round: "第一轮",
    layer: "Layer 1",
    focus: "积分概念串联",
    risk: "需要关注",
  },
  {
    id: "s-828",
    name: "828 物理化学",
    type: "专业课",
    maxScore: "150",
    targetScore: "125",
    currentProgress: "热力学第二定律",
    currentMastery: "基本理解",
    weeklyHours: "16",
    hasPastPapers: true,
    hasSolutions: true,
    hasReferences: true,
    round: "第一轮",
    layer: "Layer 2",
    focus: "熵变计算",
    risk: "高风险",
  },
];

export const seedResources: Resource[] = [
  {
    id: "r-1",
    name: "傅献彩《物理化学》第六版",
    subject: "828 物理化学",
    type: "教材",
    author: "傅献彩",
    version: "第六版",
    pages: "P132-140",
    status: "已索引",
    fileName: "physical-chemistry.pdf",
    recommendedRound: "第一轮",
    recommendedLayer: "Layer 1-2",
    currentPage: "132",
    lastRead: "今天",
    readingMinutes: "45",
    linkedNode: "热力学 / 熵与熵变",
  },
  {
    id: "r-2",
    name: "哈工大 828 历年真题",
    subject: "828 物理化学",
    type: "真题",
    author: "用户上传",
    version: "2018-2025",
    pages: "8 年",
    status: "已索引",
    fileName: "hit-828-papers.pdf",
    recommendedRound: "第一轮",
    recommendedLayer: "Layer 2-4",
    currentPage: "2025",
    lastRead: "昨天",
    readingMinutes: "30",
    linkedNode: "828 七核",
  },
];

export const seedQuestions: Question[] = [
  {
    id: "q-1",
    subject: "828 物理化学",
    school: "哈工大",
    year: "2025",
    number: "3",
    type: "简答题",
    score: "10",
    stem: "判断不同过程下熵变计算公式的适用条件。",
    answer: "先判断过程是否可逆、是否等温，再选择对应公式。",
    originalAnalysis: "原解析强调可逆过程定义。",
    aiAnalysis: "该题考查 Layer 2 的公式条件辨析，不宜直接作为综合题训练。",
    difficulty: "3",
    core: "热力学",
    branch: "熵与熵变",
    knowledge: "熵变计算",
    layer: "Layer 2",
    done: true,
    result: "错误",
    errorReason: "没有先判断过程类型",
    note: "先写条件，再代公式。",
    source: "2025 828 真题 P2",
    confirmed: true,
    favorite: true,
  },
  {
    id: "q-2",
    subject: "828 物理化学",
    school: "哈工大",
    year: "2023",
    number: "6",
    type: "计算题",
    score: "15",
    stem: "相律和自由度判断。",
    answer: "按相数、组分数和约束条件判断。",
    originalAnalysis: "原解析给出公式 F=C-P+2。",
    aiAnalysis: "适合放入相平衡 Layer 3 基础题。",
    difficulty: "2",
    core: "相平衡",
    branch: "相律",
    knowledge: "自由度判断",
    layer: "Layer 3",
    done: false,
    result: "未做",
    errorReason: "",
    note: "",
    source: "2023 828 真题 P4",
    confirmed: false,
    favorite: false,
  },
];

export const seedNodes: KnowledgeNode[] = [
  {
    id: "k-1",
    subject: "828 物理化学",
    core: "热力学",
    branch: "熵与熵变",
    knowledge: "熵变计算",
    explanation: "判断过程类型后选择熵变公式。",
    prerequisite: "可逆过程、状态函数",
    related: "热力学第二定律、化学势",
    masteryLevel: 2,
    masteryScore: 42,
    confidence: "中",
    round: "第一轮",
    layer: "Layer 2",
    mistakes: 8,
    reviewRisk: "高风险",
    isMonthlyFocus: true,
  },
  {
    id: "k-2",
    subject: "828 物理化学",
    core: "相平衡",
    branch: "相律",
    knowledge: "自由度判断",
    explanation: "根据相数、组分数和约束条件判断自由度。",
    prerequisite: "相、组分、独立变量",
    related: "相图",
    masteryLevel: 2,
    masteryScore: 48,
    confidence: "低",
    round: "第一轮",
    layer: "Layer 2",
    mistakes: 2,
    reviewRisk: "需要关注",
    isMonthlyFocus: false,
  },
];

export const seedTasks: Task[] = [
  {
    id: "t-1",
    title: "回看：熵变计算适用条件",
    subject: "828 物理化学",
    core: "热力学",
    branch: "熵与熵变",
    round: "第一轮",
    layer: "Layer 2",
    source: "傅献彩《物理化学》第六版",
    range: "P132-140",
    minutes: 70,
    standard: "不看书能判断三类熵变公式的适用条件。",
    reason: "近 15 天同类题错误集中在条件判断。",
    backup: "",
    done: false,
    actualMinutes: "",
    difficulty: "3",
    mastery: "基本理解",
    accuracy: "",
    needReview: true,
    mood: "正常",
    note: "",
    status: "待开始",
    aiRecommended: true,
    aiReasonForgetRate: "遗忘概率 82%",
    aiReasonLayerStable: "Layer 2 尚未稳定",
    aiReasonMistakeCount: "最近连续错题 8 次",
    aiReasonExamFrequency: "属于高频真题考点",
    estimatedCompletionMinutes: 60,
    masteryBefore: 48,
    masteryAfter: 72,
    startedAt: "",
    completedAt: "",
    relatedCardIds: [],
    relatedQuestionIds: [],
  },
  {
    id: "t-2",
    title: "完成 3 道基础辨析题",
    subject: "828 物理化学",
    core: "热力学",
    branch: "熵与熵变",
    round: "第一轮",
    layer: "Layer 2",
    source: "2021、2023、2025 相似真题",
    range: "已确认题 3 道",
    minutes: 55,
    standard: "正确率至少 2/3，并写出错误原因。",
    reason: "用低负荷题目验证概念是否能迁移。",
    backup: "",
    done: false,
    actualMinutes: "",
    difficulty: "2",
    mastery: "有些模糊",
    accuracy: "",
    needReview: true,
    mood: "正常",
    note: "",
    status: "待开始",
    aiRecommended: false,
    aiReasonForgetRate: "遗忘概率 45%",
    aiReasonLayerStable: "",
    aiReasonMistakeCount: "",
    aiReasonExamFrequency: "",
    estimatedCompletionMinutes: 45,
    masteryBefore: 35,
    masteryAfter: 60,
    startedAt: "",
    completedAt: "",
    relatedCardIds: [],
    relatedQuestionIds: [],
  },
];
export const seedNotes: Note[] = [
  {
    id: "n-1",
    title: "熵变计算：适用条件",
    body: "错因不是公式不会背，而是没有先判断过程类型。先写条件，再代公式。",
    tags: ["热力学", "Layer 2", "错因"],
  },
];

export const seedDecks: CardDeck[] = [
  { id: "deck-thermo", subject: "828 物理化学", name: "热力学", cardIds: ["c-1"] },
  { id: "deck-phase", subject: "828 物理化学", name: "相平衡", cardIds: [] },
  { id: "deck-kinetics", subject: "828 物理化学", name: "化学动力学", cardIds: [] },
  { id: "deck-electro", subject: "828 物理化学", name: "电化学", cardIds: [] },
  { id: "deck-exam-high-freq", subject: "828 物理化学", name: "真题高频", cardIds: [] },
  { id: "deck-math", subject: "数学二", name: "积分", cardIds: [] },
  { id: "deck-english", subject: "英语一", name: "单词与长难句", cardIds: [] },
];

export const seedCards: GrowthCard[] = [
  {
    id: "c-1",
    deckId: "deck-thermo",
    title: "理想气体恒温过程熵变公式",
    front: "理想气体恒温过程的熵变公式是什么？",
    back: "ΔS = nR ln(V₂/V₁) = nR ln(P₁/P₂)。适用条件：理想气体、恒温过程。",
    type: "公式卡",
    subject: "828 物理化学",
    core: "热力学",
    branch: "熵与熵变",
    knowledge: "熵变计算",
    source: "傅献彩《物理化学》第六版",
    page: "P132",
    modes: ["背诵", "填空", "条件辨析"],
    createdBy: "资料批注",
    createdAt: SEED_TODAY,
    lastReviewed: "未复习",
    nextReviewAt: SEED_DATE_ONLY,
    mastery: "模糊",
    note: "重点检查是否恒温。",
    favorite: true,
  },
];

export const seedAnnotations: Annotation[] = [
  {
    id: "a-1",
    resourceId: "r-1",
    resourceName: "傅献彩《物理化学》第六版",
    page: "132",
    selection: "ΔS = nR ln(V₂/V₁)",
    tag: "重点",
    note: "这个公式只有恒温过程才能直接用。",
    linkedNode: "热力学 / 熵与熵变 / 熵变计算",
    createdAt: SEED_TODAY,
    handled: false,
  },
];

export const seedAppSettings: AppSettings = {
  aiProvider: "未接入",
  modelName: "本地规则模拟",
  retrievalMode: "本机 localStorage",
  notificationTime: "21:30",
  notificationChannel: "站内提醒",
  parseMode: "AI预识别 + 用户确认",
  aiEnabled: true,
  aiConfirmBeforeAction: true,
  aiConfirmAfterRecognition: true,
  aiAnswerDetail: "标准",
  aiReadUploads: true,
  aiReadStudyRecords: true,
  aiAdjustPlan: true,
};

export const seedStudyDays: StudyDay[] = [
  { date: SEED_DATE_ONLY, completed: 1, minutes: 45 },
  { date: SEED_DATE_ONLY, completed: 2, minutes: 120 },
  { date: SEED_DATE_ONLY, completed: 1, minutes: 60 },
  { date: SEED_DATE_ONLY, completed: 2, minutes: 95 },
];